/**
 * Major Tokyo-listed companies and ETFs by name, so the 日股 ticker search finds a stock from its
 * Japanese, English or (Traditional) Chinese name. Yahoo's symbol search does not understand Japanese
 * names, so this index is searched first; Yahoo still covers everything else by code or English name.
 * [code, 日本語名, English name, aliases (Chinese names, short names, kana)]
 */
export type JpStock = readonly [code: string, ja: string, en: string, aliases?: string];

export const jpStocks: readonly JpStock[] = [
  ['7203', 'トヨタ自動車', 'Toyota Motor', '豐田汽車 豐田 トヨタ'],
  ['6758', 'ソニーグループ', 'Sony Group', '索尼 ソニー'],
  ['9984', 'ソフトバンクグループ', 'SoftBank Group', '軟銀集團 軟體銀行 軟銀 ソフトバンクG'],
  ['9434', 'ソフトバンク', 'SoftBank Corp', '軟銀電信'],
  ['6861', 'キーエンス', 'Keyence', '基恩斯'],
  ['8306', '三菱UFJフィナンシャル・グループ', 'Mitsubishi UFJ Financial Group', '三菱日聯 三菱UFJ MUFG'],
  ['8316', '三井住友フィナンシャルグループ', 'Sumitomo Mitsui Financial Group', '三井住友金融 SMFG'],
  ['8411', 'みずほフィナンシャルグループ', 'Mizuho Financial Group', '瑞穗 みずほ'],
  ['8308', 'りそなホールディングス', 'Resona Holdings', '理索納 りそな'],
  ['8309', '三井住友トラストグループ', 'Sumitomo Mitsui Trust Group', '三井住友信託'],
  ['8035', '東京エレクトロン', 'Tokyo Electron', '東京威力科創 東京威力 東京電子'],
  ['9983', 'ファーストリテイリング', 'Fast Retailing', '迅銷 優衣庫 ユニクロ UNIQLO'],
  ['7974', '任天堂', 'Nintendo', '任天堂'],
  ['8058', '三菱商事', 'Mitsubishi Corporation', '三菱商事'],
  ['8031', '三井物産', 'Mitsui & Co.', '三井物產'],
  ['8001', '伊藤忠商事', 'ITOCHU', '伊藤忠'],
  ['8002', '丸紅', 'Marubeni', '丸紅'],
  ['8053', '住友商事', 'Sumitomo Corporation', '住友商事'],
  ['8015', '豊田通商', 'Toyota Tsusho', '豐田通商'],
  ['2768', '双日', 'Sojitz', '雙日'],
  ['6501', '日立製作所', 'Hitachi', '日立'],
  ['6503', '三菱電機', 'Mitsubishi Electric', '三菱電機'],
  ['6752', 'パナソニック ホールディングス', 'Panasonic Holdings', '松下 國際牌 パナソニック'],
  ['6954', 'ファナック', 'FANUC', '發那科'],
  ['6981', '村田製作所', 'Murata Manufacturing', '村田'],
  ['6971', '京セラ', 'Kyocera', '京瓷'],
  ['6702', '富士通', 'Fujitsu', '富士通'],
  ['6701', '日本電気', 'NEC', '日本電氣'],
  ['6762', 'TDK', 'TDK', 'TDK'],
  ['6723', 'ルネサスエレクトロニクス', 'Renesas Electronics', '瑞薩 ルネサス'],
  ['6857', 'アドバンテスト', 'Advantest', '愛德萬'],
  ['6146', 'ディスコ', 'DISCO', '迪思科'],
  ['6920', 'レーザーテック', 'Lasertec', '雷泰光電'],
  ['7735', 'SCREENホールディングス', 'SCREEN Holdings', 'SCREEN'],
  ['4062', 'イビデン', 'Ibiden', '揖斐電'],
  ['6976', '太陽誘電', 'Taiyo Yuden', '太陽誘電'],
  ['3436', 'SUMCO', 'SUMCO', '勝高'],
  ['6594', 'ニデック', 'Nidec', '日本電產 尼得科'],
  ['6273', 'SMC', 'SMC', 'SMC'],
  ['6506', '安川電機', 'Yaskawa Electric', '安川電機'],
  ['6504', '富士電機', 'Fuji Electric', '富士電機'],
  ['5802', '住友電気工業', 'Sumitomo Electric Industries', '住友電工'],
  ['5803', 'フジクラ', 'Fujikura', '藤倉'],
  ['6367', 'ダイキン工業', 'Daikin Industries', '大金'],
  ['6301', '小松製作所', 'Komatsu', '小松 コマツ'],
  ['6326', 'クボタ', 'Kubota', '久保田'],
  ['7011', '三菱重工業', 'Mitsubishi Heavy Industries', '三菱重工'],
  ['7012', '川崎重工業', 'Kawasaki Heavy Industries', '川崎重工'],
  ['7013', 'IHI', 'IHI', '石川島播磨'],
  ['4063', '信越化学工業', 'Shin-Etsu Chemical', '信越化學'],
  ['4005', '住友化学', 'Sumitomo Chemical', '住友化學'],
  ['4188', '三菱ケミカルグループ', 'Mitsubishi Chemical Group', '三菱化學'],
  ['3407', '旭化成', 'Asahi Kasei', '旭化成'],
  ['3402', '東レ', 'Toray Industries', '東麗'],
  ['4091', '日本酸素ホールディングス', 'Nippon Sanso Holdings', '日本酸素'],
  ['4502', '武田薬品工業', 'Takeda Pharmaceutical', '武田藥品 武田'],
  ['4568', '第一三共', 'Daiichi Sankyo', '第一三共'],
  ['4519', '中外製薬', 'Chugai Pharmaceutical', '中外製藥'],
  ['4503', 'アステラス製薬', 'Astellas Pharma', '安斯泰來'],
  ['4523', 'エーザイ', 'Eisai', '衛采'],
  ['4507', '塩野義製薬', 'Shionogi', '鹽野義 塩野義'],
  ['4578', '大塚ホールディングス', 'Otsuka Holdings', '大塚'],
  ['4151', '協和キリン', 'Kyowa Kirin', '協和麒麟'],
  ['4543', 'テルモ', 'Terumo', '泰爾茂'],
  ['7741', 'HOYA', 'HOYA', '豪雅'],
  ['7733', 'オリンパス', 'Olympus', '奧林巴斯'],
  ['2413', 'エムスリー', 'M3', 'M3'],
  ['4661', 'オリエンタルランド', 'Oriental Land', '東方樂園 迪士尼'],
  ['4755', '楽天グループ', 'Rakuten Group', '樂天'],
  ['4689', 'LINEヤフー', 'LY Corporation', 'LINE雅虎 雅虎 ヤフー'],
  ['4385', 'メルカリ', 'Mercari', '煤爐 メルカリ'],
  ['6098', 'リクルートホールディングス', 'Recruit Holdings', '瑞可利 リクルート'],
  ['4307', '野村総合研究所', 'Nomura Research Institute', '野村總研 NRI'],
  ['4704', 'トレンドマイクロ', 'Trend Micro', '趨勢科技'],
  ['9432', '日本電信電話', 'NTT', '日本電信電話 NTT'],
  ['9433', 'KDDI', 'KDDI', 'KDDI'],
  ['9613', 'NTTデータグループ', 'NTT DATA Group', 'NTT數據'],
  ['7267', '本田技研工業', 'Honda Motor', '本田 ホンダ'],
  ['7201', '日産自動車', 'Nissan Motor', '日產 日産'],
  ['7269', 'スズキ', 'Suzuki Motor', '鈴木'],
  ['7270', 'SUBARU', 'Subaru', '速霸陸 スバル'],
  ['7261', 'マツダ', 'Mazda Motor', '馬自達'],
  ['7211', '三菱自動車工業', 'Mitsubishi Motors', '三菱汽車'],
  ['7272', 'ヤマハ発動機', 'Yamaha Motor', '山葉發動機'],
  ['7951', 'ヤマハ', 'Yamaha', '山葉'],
  ['6902', 'デンソー', 'Denso', '電裝'],
  ['5108', 'ブリヂストン', 'Bridgestone', '普利司通'],
  ['7751', 'キヤノン', 'Canon', '佳能'],
  ['4901', '富士フイルムホールディングス', 'Fujifilm Holdings', '富士軟片 富士フイルム'],
  ['7731', 'ニコン', 'Nikon', '尼康'],
  ['6724', 'セイコーエプソン', 'Seiko Epson', '愛普生 エプソン'],
  ['6753', 'シャープ', 'Sharp', '夏普'],
  ['6448', 'ブラザー工業', 'Brother Industries', '兄弟工業'],
  ['5401', '日本製鉄', 'Nippon Steel', '日本製鐵 新日鐵'],
  ['5411', 'JFEホールディングス', 'JFE Holdings', 'JFE'],
  ['5713', '住友金属鉱山', 'Sumitomo Metal Mining', '住友金屬礦山'],
  ['5020', 'ENEOSホールディングス', 'ENEOS Holdings', '引能仕 ENEOS'],
  ['1605', 'INPEX', 'INPEX', '國際石油開發帝石'],
  ['9501', '東京電力ホールディングス', 'Tokyo Electric Power', '東京電力 東電'],
  ['9503', '関西電力', 'Kansai Electric Power', '關西電力 関電'],
  ['9531', '東京瓦斯', 'Tokyo Gas', '東京瓦斯 東京ガス'],
  ['9020', '東日本旅客鉄道', 'East Japan Railway', 'JR東日本'],
  ['9022', '東海旅客鉄道', 'Central Japan Railway', 'JR東海'],
  ['9021', '西日本旅客鉄道', 'West Japan Railway', 'JR西日本'],
  ['9005', '東急', 'Tokyu', '東急'],
  ['9064', 'ヤマトホールディングス', 'Yamato Holdings', '大和運輸 黑貓 ヤマト'],
  ['9101', '日本郵船', 'NYK Line', '日本郵船'],
  ['9104', '商船三井', 'Mitsui O.S.K. Lines', '商船三井'],
  ['9107', '川崎汽船', 'Kawasaki Kisen Kaisha', '川崎汽船 K-Line'],
  ['9201', '日本航空', 'Japan Airlines', '日航 JAL'],
  ['9202', 'ANAホールディングス', 'ANA Holdings', '全日空 ANA'],
  ['8766', '東京海上ホールディングス', 'Tokio Marine Holdings', '東京海上'],
  ['8725', 'MS&ADインシュアランスグループホールディングス', 'MS&AD Insurance Group', 'MS&AD'],
  ['8630', 'SOMPOホールディングス', 'Sompo Holdings', 'SOMPO'],
  ['8750', '第一生命ホールディングス', 'Dai-ichi Life Holdings', '第一生命'],
  ['8591', 'オリックス', 'ORIX', '歐力士'],
  ['8604', '野村ホールディングス', 'Nomura Holdings', '野村'],
  ['8601', '大和証券グループ本社', 'Daiwa Securities Group', '大和證券'],
  ['6178', '日本郵政', 'Japan Post Holdings', '日本郵政'],
  ['7182', 'ゆうちょ銀行', 'Japan Post Bank', '郵儲銀行'],
  ['8801', '三井不動産', 'Mitsui Fudosan', '三井不動產'],
  ['8802', '三菱地所', 'Mitsubishi Estate', '三菱地所'],
  ['1925', '大和ハウス工業', 'Daiwa House Industry', '大和房屋'],
  ['1928', '積水ハウス', 'Sekisui House', '積水房屋'],
  ['1801', '大成建設', 'Taisei', '大成建設'],
  ['1802', '大林組', 'Obayashi', '大林組'],
  ['1812', '鹿島建設', 'Kajima', '鹿島建設'],
  ['1803', '清水建設', 'Shimizu', '清水建設'],
  ['2914', '日本たばこ産業', 'Japan Tobacco', '日本菸草 JT'],
  ['2502', 'アサヒグループホールディングス', 'Asahi Group Holdings', '朝日啤酒 朝日 アサヒ'],
  ['2503', 'キリンホールディングス', 'Kirin Holdings', '麒麟 キリン'],
  ['2587', 'サントリー食品インターナショナル', 'Suntory Beverage & Food', '三得利'],
  ['2802', '味の素', 'Ajinomoto', '味之素'],
  ['2801', 'キッコーマン', 'Kikkoman', '龜甲萬'],
  ['2269', '明治ホールディングス', 'Meiji Holdings', '明治'],
  ['2897', '日清食品ホールディングス', 'Nissin Foods Holdings', '日清'],
  ['3382', 'セブン＆アイ・ホールディングス', 'Seven & i Holdings', '7&i 7-11 セブンイレブン'],
  ['8267', 'イオン', 'AEON', '永旺'],
  ['9843', 'ニトリホールディングス', 'Nitori Holdings', '宜得利 ニトリ'],
  ['4452', '花王', 'Kao', '花王'],
  ['4911', '資生堂', 'Shiseido', '資生堂'],
  ['8113', 'ユニ・チャーム', 'Unicharm', '嬌聯 尤妮佳'],
  ['7832', 'バンダイナムコホールディングス', 'Bandai Namco Holdings', '萬代南夢宮 萬代'],
  ['9766', 'コナミグループ', 'Konami Group', '科樂美 コナミ'],
  ['9697', 'カプコン', 'Capcom', '卡普空'],
  ['3659', 'ネクソン', 'Nexon', '樂線'],
  ['9602', '東宝', 'Toho', '東寶'],
  ['7936', 'アシックス', 'ASICS', '亞瑟士'],
  ['9735', 'セコム', 'Secom', '西科姆'],
  ['1306', 'NEXT FUNDS TOPIX連動型上場投信', 'NEXT FUNDS TOPIX ETF', 'TOPIX 東證指數 ETF'],
  ['1321', 'NEXT FUNDS 日経225連動型上場投信', 'NEXT FUNDS Nikkei 225 ETF', '日經225 日経225 ETF'],
  ['1570', 'NEXT FUNDS 日経平均レバレッジ・インデックス連動型上場投信', 'NEXT FUNDS Nikkei 225 Leveraged ETF', '日經槓桿 日経レバ ETF'],
  ['2558', 'MAXIS米国株式(S&P500)上場投信', 'MAXIS S&P 500 ETF', 'S&P500 ETF'],
];

/** Lower-case, full-width folded, without spaces, dots or company suffixes. */
export const foldJpName = (value: string) => value.normalize('NFKC').toLowerCase()
  .replace(/株式会社|\(株\)|ホールディングス|holdings|corporation|corp\.?|co\.,? ?ltd\.?|inc\.?|[\s・.,'’&()（）-]/g, '');

export type JpMatch = { symbol: string; name: string; score: number };

/** Index entries matching a name or code fragment, best first. */
export function searchJpStocks(query: string, limit = 8): JpMatch[] {
  const term = foldJpName(query);
  if (!term) return [];
  const results: JpMatch[] = [];
  for (const [code, ja, en, aliases = ''] of jpStocks) {
    const names = [ja, en, ...aliases.split(' ')].map(foldJpName).filter(Boolean);
    let score = Infinity;
    if (code === term || `${code}t` === term) score = 0;
    else if (code.startsWith(term)) score = 1;
    for (const name of names) {
      if (name === term) score = Math.min(score, 0);
      else if (name.startsWith(term)) score = Math.min(score, 2);
      else if (name.includes(term)) score = Math.min(score, 3);
    }
    if (score < Infinity) results.push({ symbol: `${code}.T`, name: `${ja}（${en}）`, score });
  }
  return results.sort((a, b) => a.score - b.score || a.name.length - b.name.length).slice(0, limit);
}
